//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOutput.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XOutput.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Criado por: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Sobre&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;DPad é mapeado automaticamente&quot;,
        ///  &quot;Axes&quot;: &quot;Eixos&quot;,
        ///  &quot;Buttons&quot;: &quot;Botões&quot;,
        ///  &quot;Cancel&quot;: &quot;Cancelar&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Fechar a aplicação para a barra de tarefas&quot;,
        ///  &quot;Configure&quot;: &quot;Configurar&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Configurar Todos&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;{0} está conectado.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;{0} está desconectado.&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;Deadzone&quot;,
        ///  &quot;DiagnosticsM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Brazilian_Portuguese {
            get {
                return ResourceManager.GetString("Brazilian_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Created by: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;About&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;DPad is automatically mapped&quot;,
        ///  &quot;Axes&quot;: &quot;Axes&quot;,
        ///  &quot;Buttons&quot;: &quot;Buttons&quot;,
        ///  &quot;Cancel&quot;: &quot;Cancel&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Close application to tray bar&quot;,
        ///  &quot;Configure&quot;: &quot;Configure&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Configure All&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;{0} is connected.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;{0} is disconnected.&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;Deadzone&quot;,
        ///  &quot;DiagnosticsMenu&quot;: &quot;Diagnostics&quot;,
        ///  &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Created by: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;A Propos&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;DPad est mapper automatiquement&quot;,
        ///  &quot;Axes&quot;: &quot;Axes&quot;,
        ///  &quot;Buttons&quot;: &quot;Buttons&quot;,
        ///  &quot;Cancel&quot;: &quot;Annuler&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Reduire dans la barre des taches&quot;,
        ///  &quot;Configure&quot;: &quot;Configurer&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Configurer tout&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;{0} est connecter.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;{0} est deconnecter.&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;Deadzone&quot;,
        ///  &quot;DiagnosticsMenu&quot;: &quot;Diag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Erstellt von: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Über&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;Steuerkreuz wurde automatisch konfiguriert&quot;,
        ///  &quot;Axes&quot;: &quot;Achsen&quot;,
        ///  &quot;Buttons&quot;: &quot;Tasten&quot;,
        ///  &quot;Cancel&quot;: &quot;Abbrechen&quot;,
        ///  &quot;CloseToTray&quot;: &quot;In die Taskleiste minimieren&quot;,
        ///  &quot;Configure&quot;: &quot;Konfigurieren&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Alle konfigurieren&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;Kontroller {0} ist verbunden.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;Kontroller {0} wurde getrennt.&quot;,
        ///  &quot;DPad&quot;: &quot;Steuerkreuz&quot;,
        ///  &quot;Deadzone [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Δημιουργήθηκε από τον: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Πληροφορίες&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;Το DPad ρυθμίζεται αυτόματα&quot;,
        ///  &quot;Axes&quot;: &quot;Άξονες&quot;,
        ///  &quot;Buttons&quot;: &quot;Κουμπιά&quot;,
        ///  &quot;Cancel&quot;: &quot;Άκυρο&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Κλείσιμο της εφαρμογής στη γραμμή εργασιών&quot;,
        ///  &quot;Configure&quot;: &quot;Ρύθμιση&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Ρύθμιση Όλων&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;{0} συνδεδεμένο.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;{0} αποσυνδεδεμένο.&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;Νεκρή ζώνη&quot;,
        ///  &quot;Diagnostic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Greek {
            get {
                return ResourceManager.GetString("Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Készítette: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Névjegy&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;A DPad automatikusan megfeleltetve&quot;,
        ///  &quot;Axes&quot;: &quot;Tengelyek&quot;,
        ///  &quot;Buttons&quot;: &quot;Gombok&quot;,
        ///  &quot;Cancel&quot;: &quot;Mégse&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Alkalmazás bezárása a tálcára&quot;,
        ///  &quot;Configure&quot;: &quot;Konfigurálás&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Összes konfigurálása&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;{0} eszközhöz kapcsolódva.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;{0} eszközről lekapcsolódva.&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;Deadzone&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Программа разработана: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;О программе&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;DPad сконфигурирован автоматически&quot;,
        ///  &quot;Axes&quot;: &quot;Оси&quot;,
        ///  &quot;Buttons&quot;: &quot;Кнопки&quot;,
        ///  &quot;Cancel&quot;: &quot;Отмена&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Закрывать в трей&quot;,
        ///  &quot;Configure&quot;: &quot;Настроить&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Настроить все&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;Контроллер \&quot;{0}\&quot; подключен.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;Контроллер \&quot;{0}\&quot; отключен.&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;Мертвая зона&quot;,
        ///  &quot;Diagn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;作者：https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;关于&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;DPAD已自动映射&quot;,
        ///  &quot;Axes&quot;: &quot;轴&quot;,
        ///  &quot;Buttons&quot;: &quot;按钮&quot;,
        ///  &quot;Cancel&quot;: &quot;取消&quot;,
        ///  &quot;CloseToTray&quot;: &quot;关闭应用程序到任务栏&quot;,
        ///  &quot;Configure&quot;: &quot;配置&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;全部配置&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;{0}已连接。&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;{0}已断开连接。&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;死角&quot;,
        ///  &quot;DiagnosticsMenu&quot;: &quot;诊断&quot;,
        ///  &quot;DirectInput&quot;: &quot;DirectInput&quot;,
        ///  &quot;Disable&quot;: &quot;禁用&quot;,
        ///  &quot;Edit&quot;: &quot;编辑&quot;,
        ///  &quot;EmulationStarted&quot;: &quot;{0}被模拟为控制器 #{1}.&quot;,
        ///  &quot;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simplified_Chinese {
            get {
                return ResourceManager.GetString("Simplified_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AboutContent&quot;: &quot;Creado por: https://github.com/csutorasa&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Acerca de&quot;,
        ///  &quot;AutomaticDPad&quot;: &quot;El DPad está mapeado automáticamente&quot;,
        ///  &quot;Axes&quot;: &quot;Ejes&quot;,
        ///  &quot;Buttons&quot;: &quot;Botones&quot;,
        ///  &quot;Cancel&quot;: &quot;Cancelar&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Cerrar a la barra de tareas&quot;,
        ///  &quot;Configure&quot;: &quot;Configurar&quot;,
        ///  &quot;ConfigureAll&quot;: &quot;Configurar Todos&quot;,
        ///  &quot;ControllerConnected&quot;: &quot;{0} está conectado.&quot;,
        ///  &quot;ControllerDisconnected&quot;: &quot;{0} fue desconectado.&quot;,
        ///  &quot;DPad&quot;: &quot;DPad&quot;,
        ///  &quot;Deadzone&quot;: &quot;Zona Muerta&quot;,
        ///  &quot;DiagnosticsMenu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
    }
}
