//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOutput.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XOutput.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;FileMenu&quot;: &quot;Arquivo&quot;,
        ///	&quot;SaveMenu&quot;: &quot;Salvar configuração&quot;,
        ///	&quot;GameControllersMenu&quot;: &quot;Controladores de Jogo&quot;,
        ///	&quot;ExitMenu&quot;: &quot;Sair&quot;,
        ///	&quot;Language&quot;: &quot;Linguagem&quot;,
        ///	&quot;HelpMenu&quot;: &quot;Ajuda&quot;,
        ///	&quot;AboutMenu&quot;: &quot;Sobre&quot;,
        ///	&quot;ToolsMenu&quot;: &quot;Ferramentas&quot;,
        ///	&quot;SettingsMenu&quot;: &quot;Configurações&quot;,
        ///	&quot;CloseToTray&quot;: &quot;Fechar a aplicação para a barra de tarefas&quot;,
        ///	&quot;RunAtStartup&quot;: &quot;Abrir ao iniciar o Windows&quot;,
        ///	&quot;OtherSettings&quot;: &quot;Outras configurações&quot;,
        ///	&quot;StartWhenConnected&quot;: &quot;Iniciar a emulação quando o controle for conectado&quot;,
        ///	&quot;Ga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Brazilian_Portuguese {
            get {
                return ResourceManager.GetString("Brazilian_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FileMenu&quot;: &quot;File&quot;,
        ///  &quot;SaveMenu&quot;: &quot;Save configuration&quot;,
        ///  &quot;GameControllersMenu&quot;: &quot;Game Controllers&quot;,
        ///  &quot;ExitMenu&quot;: &quot;Exit&quot;,
        ///  &quot;Language&quot;: &quot;Language&quot;,
        ///  &quot;HelpMenu&quot;: &quot;Help&quot;,
        ///  &quot;AboutMenu&quot;: &quot;About&quot;,
        ///  &quot;ToolsMenu&quot;: &quot;Tools&quot;,
        ///  &quot;SettingsMenu&quot;: &quot;Settings&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Close application to tray bar&quot;,
        ///  &quot;RunAtStartup&quot;: &quot;Run at Windows startup&quot;,
        ///  &quot;OtherSettings&quot;: &quot;Other settings&quot;,
        ///  &quot;StartWhenConnected&quot;: &quot;Start emulation when controller is connected&quot;,
        ///  &quot;GameControllers&quot;: &quot;Game Controllers&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FileMenu&quot;: &quot;Fichier&quot;,
        ///  &quot;SaveMenu&quot;: &quot;Sauvegarder Configuration&quot;,
        ///  &quot;GameControllersMenu&quot;: &quot;Controlleur de jeu&quot;,
        ///  &quot;ExitMenu&quot;: &quot;Sortie&quot;,
        ///  &quot;Language&quot;: &quot;Langue&quot;,
        ///  &quot;HelpMenu&quot;: &quot;Aide&quot;,
        ///  &quot;AboutMenu&quot;: &quot;A Propos&quot;,
        ///  &quot;ToolsMenu&quot;: &quot;Outils&quot;,
        ///  &quot;SettingsMenu&quot;: &quot;Options&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Reduire dans la barre des taches&quot;,
        ///  &quot;RunAtStartup&quot;: &quot;lancer au demarrrage de windows&quot;,
        ///  &quot;OtherSettings&quot;: &quot;Autre Options&quot;,
        ///  &quot;StartWhenConnected&quot;: &quot;demarrer l&apos;emulation Automatiquement&quot;,
        ///  &quot;GameControllers&quot;: &quot;Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FileMenu&quot;: &quot;Datei&quot;,
        ///  &quot;SaveMenu&quot;: &quot;Konfigurationsdatei speichern&quot;,
        ///  &quot;GameControllersMenu&quot;: &quot;Spielkontrollereinstellungen&quot;,
        ///  &quot;ExitMenu&quot;: &quot;Beenden&quot;,
        ///  &quot;Language&quot;: &quot;Sprache&quot;,
        ///  &quot;HelpMenu&quot;: &quot;Hilfe&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Über&quot;,
        ///  &quot;ToolsMenu&quot;: &quot;Werkzeuge&quot;,
        ///  &quot;SettingsMenu&quot;: &quot;Einstellungen&quot;,
        ///  &quot;CloseToTray&quot;: &quot;In die Taskleiste minimieren&quot;,
        ///  &quot;RunAtStartup&quot;: &quot;Beim Windows-Start ausführen&quot;,
        ///  &quot;OtherSettings&quot;: &quot;Weitere Einstellungen&quot;,
        ///  &quot;StartWhenConnected&quot;: &quot;Emulation starten wenn ein Kontroller verbu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FileMenu&quot;: &quot;Fájl&quot;,
        ///  &quot;SaveMenu&quot;: &quot;Beállítások mentése&quot;,
        ///  &quot;GameControllersMenu&quot;: &quot;Játék vezérlők&quot;,
        ///  &quot;ExitMenu&quot;: &quot;Kilépés&quot;,
        ///  &quot;Language&quot;: &quot;Nyelv&quot;,
        ///  &quot;HelpMenu&quot;: &quot;Segítség&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Névjegy&quot;,
        ///  &quot;ToolsMenu&quot;: &quot;Eszközök&quot;,
        ///  &quot;SettingsMenu&quot;: &quot;Beállítások&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Alkalmazás bezárása a tálcára&quot;,
        ///  &quot;RunAtStartup&quot;: &quot;Indítás a Windows betöltésekor&quot;,
        ///  &quot;OtherSettings&quot;: &quot;Egyéb beállítások&quot;,
        ///  &quot;StartWhenConnected&quot;: &quot;Emuláció indítása, amikor az eszközt csatlakoztatják&quot;,
        ///  &quot;GameContr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FileMenu&quot;: &quot;Файл&quot;,
        ///  &quot;SaveMenu&quot;: &quot;Сохранить настройки&quot;,
        ///  &quot;GameControllersMenu&quot;: &quot;Игровые контроллеры&quot;,
        ///  &quot;ExitMenu&quot;: &quot;Выход&quot;,
        ///  &quot;ToolsMenu&quot;: &quot;Инструменты&quot;,
        ///  &quot;SettingsMenu&quot;: &quot;Параметры&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Закрывать в трей&quot;,
        ///  &quot;Language&quot;: &quot;Язык&quot;,
        ///  &quot;HelpMenu&quot;: &quot;Справка&quot;,
        ///  &quot;AboutMenu&quot;: &quot;О программе&quot;,
        ///  &quot;GameControllers&quot;: &quot;Игровые контроллеры&quot;,
        ///  &quot;Output&quot;: &quot;События&quot;,
        ///  &quot;ForceRefresh&quot;: &quot;Обновить&quot;,
        ///  &quot;Edit&quot;: &quot;Настроить&quot;,
        ///  &quot;Start&quot;: &quot;Запустить&quot;,
        ///  &quot;Stop&quot;: &quot;Остановить&quot;,
        ///  &quot;DirectInput&quot;: &quot;Di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FileMenu&quot;: &quot;文件&quot;,
        ///  &quot;SaveMenu&quot;: &quot;保存配置&quot;,
        ///  &quot;GameControllersMenu&quot;: &quot;游戏控制器&quot;,
        ///  &quot;ExitMenu&quot;: &quot;退出&quot;,
        ///  &quot;Language&quot;: &quot;语言&quot;,
        ///  &quot;HelpMenu&quot;: &quot;帮助&quot;,
        ///  &quot;AboutMenu&quot;: &quot;关于&quot;,
        ///  &quot;ToolsMenu&quot;: &quot;工具&quot;,
        ///  &quot;SettingsMenu&quot;: &quot;设置&quot;,
        ///  &quot;CloseToTray&quot;: &quot;关闭应用程序到任务栏&quot;,
        ///  &quot;RunAtStartup&quot;: &quot;在Windows启动时运行&quot;,
        ///  &quot;OtherSettings&quot;: &quot;其他设置&quot;,
        ///  &quot;StartWhenConnected&quot;: &quot;连接控制器时启动模拟&quot;,
        ///  &quot;GameControllers&quot;: &quot;游戏控制器&quot;,
        ///  &quot;Output&quot;: &quot;输出&quot;,
        ///  &quot;ForceRefresh&quot;: &quot;强制刷新&quot;,
        ///  &quot;Edit&quot;: &quot;编辑&quot;,
        ///  &quot;Start&quot;: &quot;开始&quot;,
        ///  &quot;Stop&quot;: &quot;停止&quot;,
        ///  &quot;DirectInput&quot;: &quot;DirectInput&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simplified_Chinese {
            get {
                return ResourceManager.GetString("Simplified_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;FileMenu&quot;: &quot;Archivo&quot;,
        ///  &quot;SaveMenu&quot;: &quot;Guardar configuración&quot;,
        ///  &quot;GameControllersMenu&quot;: &quot;Dispositivos de juego&quot;,
        ///  &quot;ExitMenu&quot;: &quot;Salir&quot;,
        ///  &quot;Language&quot;: &quot;Idioma&quot;,
        ///  &quot;HelpMenu&quot;: &quot;Ayuda&quot;,
        ///  &quot;AboutMenu&quot;: &quot;Acerca de&quot;,
        ///  &quot;ToolsMenu&quot;: &quot;Herramientas&quot;,
        ///  &quot;SettingsMenu&quot;: &quot;Opciones&quot;,
        ///  &quot;CloseToTray&quot;: &quot;Cerrar a la barra de tareas&quot;,
        ///  &quot;RunAtStartup&quot;: &quot;Ejecutar al inicio de windows&quot;,
        ///  &quot;OtherSettings&quot;: &quot;Otras opciones&quot;,
        ///  &quot;StartWhenConnected&quot;: &quot;Iniciar la emulación cuando el control es conectado&quot;,
        ///  &quot;GameC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
    }
}
